### ISSUE TITLE
License is valid, but page shows "License Required" since update to 2.2.1-ee

### ISSUE THREAD

**Issue by lucasbroennimann** [cibseven/cibseven#428]
### Environment (Required on creation)
2.2.1-ee

### Description (Required on creation; please attach any relevant screenshots, stacktraces, log files, etc. to the ticket)
We updated from 2.1.1-ee to 2.2.1-ee. Now we have the following issue:
In System - License Key the key is shown as valid and displays customer name and expiry date correctly. However, when I navigate to any page requiring the licence, e.g. /webapp/#/seven/auth/instances/search/history, the page shows me "License Required:A valid license is required to access all features."
There are no error logs in the application itself, but the browser logs shows:

cibseven-components.es-BwVz5xDk.js:25 Error: [LicensedComponent] SW token not synced: no-token
    at loader (main-BLdwB-We.js:2:35770)

Important: We have a custom security for our application which uses a SAML token. This works perfectly fine otherwise, only since 2.2.1-ee we have this issue with the license. We also route everything with server.servlet.context-path to /kontakt (for example) which has caused issues in the past.

Some additional information:
- The service worker sw-license-v3.js for the page is active and shows the correct scope (  http://localhost/delegate/kontakt/webapp/ and the client is http://localhost/delegate/kontakt/webapp/#/seven/auth/instances/search/history )
- navigator.serviceWorker.controller always returns null
- Same behavior in Chrome and in Firefox, also in incognito window

### Steps to reproduce (Required on creation)
Don't use a standard jwt, enter a correct license, then go to any page requiring the license. 

### Observed Behavior (Required on creation)
Page shows "License Required:A valid license is required to access all features." and throws error in browser console. 

### Expected behavior (Required on creation)
With a valid licence I should be able to access the page. Also, an error with the token handling should not be reported as an issue with the license to the user.

### Solution Ideas
The check here seems to be the issue, with the first part saying the license is valid, but then calling this tokenSynced which doesn't seem to work in our setup:

nh.getLicenseStatus = function(){ return ze.get(je()+"/system/license/status") };
setup(t){
  const n = Je(() => es.state.licenseStore.isLicenseValid);
  is(async () => {
    if (es.state.licenseStore.isLicenseValid === void 0)
      await es.dispatch("licenseStore/checkLicense");   // GET /system/license/status
  });
  const i = Je(() => n.value === void 0 ? null : n.value
    ? wF({   // = Vue's defineAsyncComponent
        loader: async () => {
          const r = await E3.ensureTokenSynced();               // <-- SW sync
          if (!r.ok) throw new Error(`[LicensedComponent] SW token not synced: ${r.reason}`);
          return t.loader();                                    // <-- only now import the real chunk
        },
        errorComponent: () => Ub(Q_, {cssClass: t.cssClass}),    // <-- Q_ = "License Required" banner
        onError(r,a,o,l){ l<=3 ? a() : o() }                     // retries 3x, then gives up
      })
    : () => Ub(Q_, {cssClass: t.cssClass})   // shown when isLicenseValid === false
  );
}

**Comment by dmitrymalk** [comment]
Thank you for reaching out, and for the level of detail — it made this quick to locate.

Since 2.2.0 the enterprise features carry an additional protection that expects the authentication token to be present in browser storage (key `token`, in `sessionStorage` or `localStorage`). Only our built-in login flows write it there, so an integration that authenticates the user before the application starts — as yours does — leaves it empty. 2.1.x had no such requirement, which is why the upgrade surfaced it.

We are currently considering how best to cover setups like yours. We do not intend to remove the protection itself.

As a possible workaround in the meantime, you can store the token your provider issues, once, after authentication:

```javascript
localStorage.setItem('token', '<the token your provider issues>')
```

To work out which fix fits your deployment, two questions:

1. Do your `/services/v1/...` requests carry an `Authorization` request header, or only cookies?
2. Does your custom user provider accept a token from the `Authorization` header, or does it authenticate solely from the SAML session?

We will update this issue as we progress.

**Comment by lucasbroennimann** [comment]
Thank you for your response. I did some further debugging (with some AI assistance) and tried the workaround:
 
1. Authorization header vs. cookie: Only one call carries an explicit Authorization header — the initial bootstrap/login request, GET /services/v1/auth. Its value is a byte-for-byte copy of a (non-HttpOnly) authorization cookie that's also set on the session; every other request relies on that same-origin cookie riding along automatically, not an explicit header.

2. Does your user provider accept a token from that header? Yes — our custom IUserProvider reads request.getHeader("Authorization") on that bootstrap call and authenticates from it directly (not from a server-side SAML session lookup). We confirmed this in the logs (auth successful {userID: 'bn-admin', ...}).Given that, we tested your suggested workaround directly: since the token is readable client-side via document.cookie (not HttpOnly), we extracted the same string already proven to authenticate successfully at /services/v1/auth and ran:localStorage.setItem('token', '<that value>')
After a hard reload, localStorage.getItem('token') correctly returns the token — but the console still logs [LicensedComponent] SW token not synced: no-controller, and "License Required" persists on every gated page.


Looking at ServiceWorkerTokenManager.ensureTokenSynced(), this is expected: it calls _awaitController() and returns {ok: false, reason: "no-controller"} before it ever reaches getCurrentToken(). So populating localStorage doesn't help us — we're blocked earlier in the chain, by the issue we described in our original report: navigator.serviceWorker.controller stays permanently null even though sw-license-v3.js shows ACTIVATED/RUNNING.This happens for us behind a path-rewriting reverse proxy/API gateway (/delegate/kontakt/webapp/...).


For reference, here's the relevant part of our IUserProvider implementation (SimpleUserProvider, wired via cibseven.webclient.user.provider) 

public class SimpleUserProvider extends BaseUserProvider<StandardLogin> {

    @Override
    public User getUserInfo(User user, String userId) {
        if (user.getId().compareTo(userId) == 0) {
            // The webapp itself should not receive the token, as this would cause it to
            // do further calls with it, which causes issues on customer side
            CIBUser userWithoutToken = new CIBUser(userId);
            userWithoutToken.setDisplayName(userId);
            return userWithoutToken;
        } else {
            throw new AuthenticationException(userId);
        }
    }

    @Override
    public Object authenticateUser(HttpServletRequest request) {
        String userId = RequestSecurityContext.getUserInfo().getLoginId();
        CIBUser user = new CIBUser(userId);
        user.setDisplayName(userId);
        user.setAuthToken(request.getHeader("Authorization"));
        return user;
    }
    // ... deserialize/serialize/login follow the same pattern
}

**Comment by dmitrymalk** [comment]
Thanks your reading is correct: _awaitController() returns before getCurrentToken() is reached, so with no controller the stored token cannot help.

We found the cause. clients.claim() only runs inside the service worker's activate handler, and activate does not fire again for a worker that is already activated — so after a hard reload nothing ever claims the page and it stays uncontrolled. The page now asks to be claimed explicitly.

The fix is in review and will go out in an upcoming 2.2.x patch release. With it, the localStorage workaround should work for you — worth re-testing at that point.

**Comment by lucasbroennimann** [comment]
Thank you very much. We will retest again once the patch release is available, but stay on 2.1.1-ee for the time being.

**Comment by lucasbroennimann** [comment]
We have upgraded to version 2.2.3-ee and tested it. It did work, but still needed the workaround of having the token in the local storage. For now we added a LicenseTokenInjectionFilter which reads the token cookie and then adds a sessionStorage.setItem('token',<token>) script to the page. I don't like this workaround too much, but it does seem to get the job done. Still, thank you for the fix.

What I don't quite understand is in the release notes of 2.2.3-ee it said something about "Fixed licensed chunk authentication to use a token cookie instead of its previous mechanism" - Is this not also related to our issue or am I mistaken here?

**Comment by dmitrymalk** [comment]
@lucasbroennimann  Glad it works again, the release note was wrong, sorry. Corrected now: [2.2.3-ee release notes → License](https://docs.cibseven.org/manual/latest/release-notes/release-notes-2.2.3-ee/#license-ee-exclusive).

What 2.2.3-ee actually contains is the service worker claim fix — the `no-controller` problem you diagnosed, and why it works for you now — plus a new property that is meant to replace your workaround, but has to be set explicitly:

```yaml
cibseven:
  webclient:
    license:
      chunk:
        trustServerAuthentication: true
```

Today, when the webclient finds no token in browser storage, it gives up before sending the request — the chunk is never fetched, and you get "License Required" without the server ever being asked. That is the behaviour your `sessionStorage` injection works around.

With the property set, the webclient sends the request anyway. It arrives at `LicensedResourceFilter`, which calls your `IUserProvider.authenticateUser(request)` exactly as it does for a REST call, and serves the chunk if that succeeds. Nothing is relaxed on the server side: if your provider cannot authenticate the request, it is still refused with `403` and you still see "License Required".

So whether this replaces your filter comes down to one question. A chunk request is a plain static GET, e.g. `.../webapp/assets/ProcessInstancesSearch-a1b2c3.js` — not a `/services/v1/...` path. Your `SimpleUserProvider` authenticates from `RequestSecurityContext.getUserInfo()`, so the property helps only if your SAML filter chain populates that context for those static requests too. If it only runs for the REST paths, the request will still be refused and the property on its own will not get you anywhere.

**Comment by lucasbroennimann** [comment]
Ah, this looks very good, thank you. Unfortunately I'm going on vacation now, so I won't have time to try it out for a while. Once I get back, I'll try it out.
